# Generated by Django 3.2 on 2023-03-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_connection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='biograghy',
        ),
        migrations.AddField(
            model_name='connection',
            name='biography',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
