# Generated by Django 3.2 on 2022-12-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='AccountToken',
        ),
    ]
