# Generated by Django 3.2 on 2023-02-13 20:40

import Gp_Backend.s3_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230208_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=Gp_Backend.s3_storages.MediaStorage, upload_to='profile/'),
        ),
    ]
