# Generated by Django 3.2 on 2023-02-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230208_1507'),
        ('accounts', '0006_alter_profile_image'),
    ]

    operations = [
    ]
